# Generated by Django 5.2.1 on 2026-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_amount_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_method',
            field=models.CharField(default='khalti', max_length=20),
        ),
    ]
