# Generated by Django 6.0.1 on 2026-04-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('stripe', 'Stripe')], default='khalti', max_length=20),
        ),
    ]
