# Generated by Django 6.0.1 on 2026-02-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sell_cars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sell_requests.sellcarrequest')),
            ],
        ),
    ]
